--상품테이블 생성
CREATE TABLE PRODUCTS(
 PCODE INT NOT NULL PRIMARY KEY, 
 PNAME VARCHAR(200) NOT NULL,
 PPRICE INT DEFAULT 0
 );
 
 --테이블 삭제
 --DROP TABLE PRODUCTS;
 
 --테이블 정보 확인
 DESC PRODUCTS;
 
 --샘플데이터 입력
 INSERT INTO PRODUCTS(PCODE,PNAME, PPRICE)
 VALUES(100,'삼성 냉장고',2500000);
 INSERT INTO PRODUCTS(PCODE,PNAME, PPRICE)
 VALUES(101,'엘지 냉장고',2800000);
  INSERT INTO PRODUCTS(PCODE,PNAME, PPRICE)
 VALUES(102,'엘지 세탁기',2300000);
  INSERT INTO PRODUCTS(PCODE,PNAME, PPRICE)
 VALUES(103,'삼성 세탁기',2700000);
 
 CREATE SEQUENCE PCODE_SEQ START WITH 104 INCREMENT BY 1;
 INSERT INTO PRODUCTS(PCODE, PNAME, PPRICE) 
 VALUES(PCODE_SEQ.NEXTVAL, '삼성스타일러',1700000);


--모든 데이터 출력
SELECT * FROM PRODUCTS;



-- 판매테이블 생성
CREATE TABLE SALE(
 SCODE INT NOT NULL PRIMARY KEY,
 PCODE INT NOT NULL,
 QNT INT DEFAULT 1,
 SPRICE INT DEFAULT 0, -- 판매가격
 SDATE DATE DEFAULT SYSDATE, -- 현재 날짜와 시간
 FOREIGN KEY(PCODE) REFERENCES PRODUCTS(PCODE)--외래키(참조키)
 );
 
 -- 자동증가 판매코드 시퀀스
CREATE SEQUENCE CODE_SEQ START WITH 1 INCREMENT BY 1; // 시퀀스 이름은 중복되면 안됨
--SELECT CODE_SEQ NEXTVAL FROM DUAL;

 --판매테이블 샘플데이터
 INSERT INTO SALE(SCODE,PCODE,QNT,SPRICE)
 VALUES(CODE_SEQ.NEXTVAL,100,2,2500000);
 INSERT INTO SALE(SCODE,PCODE,QNT,SPRICE)
 VALUES(CODE_SEQ.NEXTVAL,100,3,2400000);
 INSERT INTO SALE(SCODE,PCODE,QNT,SPRICE)
 VALUES(CODE_SEQ.NEXTVAL,101,1,2800000);
 INSERT INTO SALE(SCODE,PCODE,QNT,SPRICE)
 VALUES(CODE_SEQ.NEXTVAL,101,1,2800000);
 
 SELECT * FROM SALE;
 
 SELECT * FROM SALE where pcode =100;
 
CREATE VIEW VIEW_SALE AS --SQL 복잡하면 뷰(가상테이블)
SELECT s*, P.PNAME
S.QNT,S.SPRICE*S.QNT SSUM, P.PPRICE, 
TO_CHAR(S.SDATE, 'YYYY-MM-DD HH:MI:ss')FDATE
FROM SALE S, PRODUCTS P -- 별명 줌
WHERE P.PCODE = S.PCODE
ORDER BY S.SCODE DESC;
 
 SELECT * FROM SALE WHERE PCODE = 101;
 
 SELECT * FROM VIEW_SALE WHERE PNAME LIKE '%삼성%' order by scode desc;
 
 COMMIT;
 
 --drop table sale;
 --drop table products;
 
 create view view_sale1 as
 select s.*, p.pname
 FROM SALE S, PRODUCTS P 
 where s.pcode = p.pcode;
 
 SELECT pcode, pname, sum(qnt),sum(qnt*sprice) FROM view_sale1
 group by PCODE, pname
 order by pcode;
 
 COMMIT;
/* 
cREATE VIEW VIEW_SALE AS --SQL 복잡하면 뷰(가상테이블)
SELECT s*, P.PNAME
FROM SALE S, PRODUCTS P -- 별명 줌
WHERE P.PCODE = S.PCODE
ORDER BY S.SCODE DESC; */